multi.lineplot <- function(fechas, var, color, titulo, intervalo, ejes, t='l', lwd=2, ylim1=c(min(get(var[1]))*0.9, max(get(var[1]))*1.1), ylim2=c(min(get(var[2]))*0.9, max(get(var[2]))*1.1), xaxs="r", cex.main=1, at=NULL, labels=TRUE, ...) {
  if (is.null(titulo) || titulo == "") {
    par(mar=c(2,4,0.1,4), mfrow=c(1, 1), family="Times")
    cxlims <- c(min(fechas), max(fechas))
    plot(fechas, get(var[1]), t=t, col=color[1], lwd=lwd, axes=F, xlab='', ylab='', xlim=cxlims, ylim=ylim1, xaxs=xaxs, main=NULL, cex.main=cex.main, ...)
    yticks1 <- axis(2, lwd=0, lwd.tick=1, tck=0.02, at=at, labels=labels)
    par(new=TRUE)
    plot(fechas, get(var[2]), t=t, col=color[2], lwd=lwd, axes=F, xlab='', ylab='', xlim=cxlims, ylim=ylim2, xaxs=xaxs, ...)
    yticks2 <- axis(4, lwd=0, lwd.tick=1, tck=0.02, at=at, labels=labels)
    xticks <- axis.Date(1, x=fechas, at=seq(fechas[1], fechas[length(fechas)], intervalo) , lwd=0, lwd.tick=1, tck=0.02)
    axis.Date(3, x=fechas, at=seq(fechas[1], fechas[length(fechas)], intervalo), lwd=0, lwd.tick=1, tck=0.02, lab=F)
    abline(h=yticks1, lty=3, lw=0.5)
    abline(h=yticks2, lty=3, lw=0.5)
    abline( v=xticks, lty=3 ,lw=0.5)
    box()
    mtext(ejes[1], side=2, line=3)
    mtext(ejes[2], side=4, line=3)
  } else
    par(mar=c(2,4,1.5,4), mfrow=c(1, 1), family="Times")
  cxlims <- c(min(fechas), max(fechas))
  plot(fechas, get(var[1]), t=t, col=color[1], lwd=lwd, axes=F, xlab='', ylab='', xlim=cxlims, ylim=ylim1, xaxs=xaxs, main=titulo, cex.main=cex.main, ...)
  yticks1 <- axis(2, lwd=0, lwd.tick=1, tck=0.02, at=at, labels=labels)
  par(new=TRUE)
  plot(fechas, get(var[2]), t=t, col=color[2], lwd=lwd, axes=F, xlab='', ylab='', xlim=cxlims, ylim=ylim2, xaxs=xaxs, ...)
  yticks2 <- axis(4, lwd=0, lwd.tick=1, tck=0.02, at=at, labels=labels)
  xticks <- axis.Date(1, x=fechas, at=seq(fechas[1], fechas[length(fechas)], intervalo) , lwd=0, lwd.tick=1, tck=0.02)
  axis.Date(3, x=fechas, at=seq(fechas[1], fechas[length(fechas)], intervalo), lwd=0, lwd.tick=1, tck=0.02, lab=F)
  abline(h=yticks1, lty=3, lw=0.5)
  abline(h=yticks2, lty=3, lw=0.5)
  abline(v=xticks, lty=3 ,lw=0.5)
  box()
  mtext(ejes[1], side=2, line=3)
  mtext(ejes[2], side=4, line=3)
}